### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by swaminator** [nchah/github-traffic-stats#13]
I get the following error when I run `gts 'swaminator' 'nikhil' 'save_csv'`

`requests.exceptions.SSLError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/swaminator/nikhil/traffic/views (Caused by SSLError(SSLError(1, u'[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)'),))`

Any idea why?

**Comment by nchah** [comment]
Hi,

I haven't encountered that error myself, but could this be similar to the question raised at https://stackoverflow.com/questions/44316292/ssl-sslerror-tlsv1-alert-protocol-version ? The top 2 answers seem to have detailed writeups.

**Comment by swaminator** [comment]
I fixed it. My terminal was using an older version of Python (2.7). Updated my bash_profile to point to the latest version of Python.
