### ISSUE TITLE
enhancement: also track clones and referrers

### ISSUE THREAD

**Issue by thirschbuechler** [nchah/github-traffic-stats#3]
It would be awesome if clones and referrers would be tracked as well, as specified in the [official api](https://developer.github.com/v3/repos/traffic/).

I've tried copy-pasting the `traffic`-sections and modifying them to also track clones, but my understanding of json and the involved datastructures in the py-script seem to be too limited.

**Comment by nchah** [comment]
Thanks for the suggestion. I'll look into this as well when I have time.

**Comment by nchah** [comment]
Had some time to add this functionality. The script now gets 'clones' and 'referrer' stats, and can also store them as CSV. :)

**Comment by thirschbuechler** [comment]
Awesome, thanks dude!
